		<link href='../Styles.css' rel='stylesheet' type='text/css'>
		<meta name="vs_defaultClientScript" content="JavaScript">
		<meta name="vs_targetSchema" content="http://schemas.microsoft.com/intellisense/ie5">
		<meta name="description" content="Viva Les Amis -- A documentary by Nancy Higgins. The film explores the 27 year history of Les Amis Café – a sidewalk café that served almost three decades of eclectic customers and staff.">
		<meta name="keywords" content="Viva Les Amis, Austin, Texas, French, cuisine, food, restaurant, Nancy Higgins, Alan Pogue, Newman Stribling">